version: '2'

services:
  app_1:
    build:
      context:  ./app
      dockerfile: Dockerfile
      args:
        - ARG1=You deploy the service app_1
    expose:   
      - "80"
  app_2:
    build:
      context:  ./app
      dockerfile: Dockerfile
      args:
        - ARG1=You deploy the service app_2
    expose:
      - "80"
  app_3:
    build:
      context:  ./app
      dockerfile: Dockerfile
      args:
        - ARG1=You deploy the service app_3
    expose:
      - "80"
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    environment:
        - WORKER_PROCESSES=${WORKER_PROCESSES}
    ports:
      - "8080:80"
    links:
      - app_1
      - app_2
      - app_3
